title = 'leo homestuck'
description = 'bad ideas 2k21'

# The URL the site will be built for
base_url = "https://vriska.dev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "Ergo"

generate_feed = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
profile = 'vriska2.png'
color_themes = ["dark", "light"]

[[extra.socials]]
icon = "github"
display = "leo60228"
uri = "https://github.com/leo60228"

[[extra.socials]]
icon = "gitlab"
display = "vriska"
uri = "https://gitlab.com/vriska"

[[extra.socials]]
icon = "twitter"
display = "@leo60228"
uri = "https://twitter.com/leo60228"

[[extra.socials]]
icon = "mastodon"
display = "@leo@60228.dev"
uri = "https://60228.dev/@leo"

[[extra.socials]]
icon = "tumblr"
display = "leo60228"
uri = "https://leo60228.tumblr.com"

[extra.comments]
repo = "leo60228/leoblog"
theme = "github-dark"
label = "comment"
term = "pathname"

[extra.font_awesome]
kit = "e307e34624"
