media_folder: "static/img/uploads"
public_folder: "/img/uploads"

backend:
    name: git-gateway
    branch: main

collections:
    - name: "blog"
      label: "Blog"
      folder: "content"
      create: true
      fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Date"
            name: "date"
            widget: "datetime"
            format: "YYYY-MM-DD"
            date_format: true
            time_format: false
          - label: "Category"
            name: "category"
            widget: "string"
